site_name: WiseUpData
site_author: Silvio Liborio
site_description: >-
  Data solutions for a data-driven world 🌎🔍📈
site_url: https://wiseupdata.github.io/wiseupdata/

# Copyright
copyright: Copyright &copy; 2023 - 2023 Silvio Liborio

watch: [README.md]

theme:
  name: 'material'
  # custom_dir: assets/overrides/html
  favicon: "https://raw.githubusercontent.com/wiseupdata/strplus/main/assets/imgs/python.png"
  logo: "https://raw.githubusercontent.com/wiseupdata/strplus/main/assets/imgs/python.png"
  palette:
    - scheme: slate
      primary: pink
      accent: lime
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
  font:
    text: Roboto
    code: Roboto Mono
    features:
      - search.suggest
      - search.highlight
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - navigation.footer
      - navigation.indexes
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - footnotes
  icon:
    repo: fontawesome/brands/github-alt
  language: en
repo_name: wiseupdata/strplus
repo_url: https://github.com/wiseupdata/strplus


extra_css:
  - themes/strplus.css

plugins:
  - search 
  - section-index 

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Pages
- admonition
- pymdownx.highlight
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true

# language options
extra:
  alternate:
    - link: https://wiseupdata.github.io/wiseupdata/
      name: English